version: '3.8'

services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost/api
    ports:
      - "3000:3000"

networks:
  default:
    name: nginx_network
    external: true