version: '3.8'

services:
  nginx:
    container_name: nginx_proxy
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '443:443'
    networks:
      - nginx

networks:
  nginx:
    name: nginx_network
    external: true
